package ma.dari.api.contract;

import com.google.firebase.auth.FirebaseToken;
import ma.dari.api.listing.AvailabilityState;
import ma.dari.api.listing.Listing;
import ma.dari.api.listing.ListingRepository;
import ma.dari.api.listing.ListingStatus;
import ma.dari.api.messaging.Conversation;
import ma.dari.api.messaging.ConversationRepository;
import ma.dari.api.support.AbstractIntegrationTest;
import ma.dari.api.user.User;
import ma.dari.api.user.UserRepository;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import static io.restassured.RestAssured.given;
import static org.assertj.core.api.Assertions.assertThat;

/**
 * Wire-format snapshots for representative public and authenticated API
 * responses. Values generated by persistence (identifiers and instants) stay
 * dynamic; every client-visible field, null, scalar representation and order
 * is fixed here.
 */
class JsonWireContractApiTest extends AbstractIntegrationTest {

    private static final List<String> PUBLIC_DETAIL_FIELDS = List.of(
            "id", "title", "city", "neighborhood", "priceRent", "priceDeposit", "description",
            "wifiIncluded", "electricityIncluded", "waterIncluded", "propertyType", "numBedrooms",
            "numBathrooms", "roomType", "roomFurnishing", "commonAreasFurnished", "availableFrom",
            "minStayMonths", "latitude", "longitude", "availabilityState", "createdAt", "updatedAt",
            "amenityCodes", "photos", "houseRules", "rooms", "owner");
    /** The host block: the public-profile subset, and nothing that could contact or identify them further. */
    private static final List<String> LISTING_HOST_FIELDS = List.of(
            "id", "displayName", "avatarUrl", "verification", "memberSince");
    private static final List<String> SEARCH_PAGE_FIELDS = List.of("items", "nextCursor", "hasMore");
    private static final List<String> PUBLIC_LISTING_FIELDS = List.of(
            "id", "title", "city", "neighborhood", "priceRent", "latitude", "longitude",
            "availabilityState", "createdAt", "updatedAt", "coverPhotoUrl");
    private static final List<String> ERROR_FIELDS = List.of("code", "message");
    private static final List<String> CONVERSATION_FIELDS = List.of(
            "id", "listingId", "participantAId", "participantBId", "otherUserId", "otherUserDisplayName",
            "createdAt", "lastMessage", "lastMessageAt", "unreadCount", "lastMessageId", "lastMessageReadAt");

    @Autowired
    UserRepository users;

    @Autowired
    ListingRepository listings;

    @Autowired
    ConversationRepository conversations;

    @Autowired
    ObjectMapper json;

    @Test
    @DisplayName("representative API JSON shapes remain stable")
    void wireSnapshotsRemainStable() throws Exception {
        String suffix = UUID.randomUUID().toString().substring(0, 8);
        String city = "ContractCity" + suffix;
        User owner = users.saveAndFlush(new User("contract-owner-" + suffix,
                "contract-owner-" + suffix + "@example.ma", true, "Contract Owner"));
        User seeker = users.saveAndFlush(new User("contract-seeker-" + suffix,
                "contract-seeker-" + suffix + "@example.ma", true, "Contract Seeker"));

        Listing representative = saveListing(owner, city, "Contrat public", 0);
        for (int index = 1; index <= 20; index++) {
            saveListing(owner, city, "Contrat recherche " + index, index);
        }

        JsonNode detail = read(given().when().get("/listings/{id}", representative.getId())
                .then().statusCode(200).extract().asString());
        assertThat(fieldNames(detail)).containsExactlyElementsOf(PUBLIC_DETAIL_FIELDS);
        assertThat(detail.path("title").asText()).isEqualTo("Contrat public");
        assertThat(detail.path("priceRent").decimalValue()).isEqualByComparingTo("2200.00");
        assertThat(detail.path("availabilityState").asText()).isEqualTo("AVAILABLE");
        assertThat(detail.path("priceDeposit").isNull()).isTrue();
        assertThat(detail.path("photos").size()).isZero();
        assertThat(detail.path("houseRules").isNull()).isTrue();
        assertThat(detail.path("createdAt").asText()).matches("\\d{4}-\\d{2}-\\d{2}T.*Z");
        JsonNode host = detail.path("owner");
        assertThat(fieldNames(host)).containsExactlyElementsOf(LISTING_HOST_FIELDS);
        assertThat(host.path("id").asText()).isEqualTo(owner.getId().toString());
        assertThat(host.path("displayName").asText()).isEqualTo("Contract Owner");
        assertThat(host.path("avatarUrl").isNull()).isTrue();
        assertThat(host.path("verification").asText()).isEqualTo("EMAIL");
        assertThat(host.path("memberSince").asText()).matches("\\d{4}-\\d{2}-\\d{2}T.*Z");
        assertThat(host.toString())
                .doesNotContain(owner.getEmail())
                .doesNotContain(owner.getFirebaseUid())
                .doesNotContain("ACTIVE");

        JsonNode search = read(given().queryParam("city", city).queryParam("sort", "recent")
                .when().get("/listings").then().statusCode(200).extract().asString());
        assertThat(fieldNames(search)).containsExactlyElementsOf(SEARCH_PAGE_FIELDS);
        assertThat(search.path("items").size()).isEqualTo(20);
        assertThat(search.path("hasMore").asBoolean()).isTrue();
        assertThat(search.path("nextCursor").asText()).isNotBlank();
        assertThat(fieldNames(search.path("items").get(0))).containsExactlyElementsOf(PUBLIC_LISTING_FIELDS);
        assertThat(search.path("items").get(0).path("coverPhotoUrl").isNull()).isTrue();

        JsonNode error = read(given().when().get("/listings/{id}", UUID.randomUUID())
                .then().statusCode(404).extract().asString());
        assertThat(fieldNames(error)).containsExactlyElementsOf(ERROR_FIELDS);
        assertThat(error.path("code").asText()).isEqualTo("NOT_FOUND");
        assertThat(error.path("message").asText()).isEqualTo("Annonce introuvable");

        Conversation conversation = conversations.saveAndFlush(new Conversation(representative, owner, seeker));
        stubToken(seeker.getFirebaseUid(), seeker.getEmail());
        JsonNode conversationPage = read(given().header("Authorization", "Bearer contract-token")
                .when().get("/conversations/{id}", conversation.getId()).then().statusCode(200).extract().asString());
        assertThat(fieldNames(conversationPage)).containsExactlyElementsOf(CONVERSATION_FIELDS);
        assertThat(conversationPage.path("listingId").asText()).isEqualTo(representative.getId().toString());
        assertThat(conversationPage.path("otherUserDisplayName").asText()).isEqualTo("Contract Owner");
        assertThat(conversationPage.path("lastMessage").isNull()).isTrue();
        assertThat(conversationPage.path("lastMessageAt").isNull()).isTrue();
        assertThat(conversationPage.path("lastMessageId").isNull()).isTrue();
        assertThat(conversationPage.path("lastMessageReadAt").isNull()).isTrue();
        assertThat(conversationPage.path("unreadCount").asLong()).isZero();
    }

    private Listing saveListing(User owner, String city, String title, int index) {
        return listings.saveAndFlush(new Listing(owner, title, city, "Centre", 33.9716 + (index * 0.0001),
                -6.8498, new BigDecimal("2200.00"), ListingStatus.PUBLISHED, AvailabilityState.AVAILABLE));
    }

    private void stubToken(String uid, String email) throws Exception {
        FirebaseToken token = Mockito.mock(FirebaseToken.class);
        Mockito.when(token.getUid()).thenReturn(uid);
        Mockito.when(token.getEmail()).thenReturn(email);
        Mockito.when(token.isEmailVerified()).thenReturn(true);
        Mockito.when(firebaseAuth.verifyIdToken(Mockito.anyString())).thenReturn(token);
    }

    private JsonNode read(String body) {
        return json.readTree(body);
    }

    private static List<String> fieldNames(JsonNode node) {
        return new ArrayList<>(node.propertyNames());
    }
}
