-- Postgres enums, not VARCHAR + CHECK. They are harder to alter, which is the
-- point: a typo in a status string becomes an error instead of an invisible bug.
CREATE TYPE user_role   AS ENUM ('USER', 'ADMIN');
CREATE TYPE user_status AS ENUM ('ACTIVE', 'SUSPENDED', 'BANNED');

CREATE TABLE users (
    id              UUID PRIMARY KEY,               -- UUIDv7, generated by the app
    firebase_uid    TEXT        NOT NULL UNIQUE,    -- the join to the Firebase identity
    email           TEXT        NOT NULL,
    email_verified  BOOLEAN     NOT NULL DEFAULT FALSE,
    phone           TEXT,
    phone_verified  BOOLEAN     NOT NULL DEFAULT FALSE,
    first_name      TEXT,
    display_name    TEXT        NOT NULL,           -- the only name shown publicly
    role            user_role   NOT NULL DEFAULT 'USER',
    status          user_status NOT NULL DEFAULT 'ACTIVE',
    city            TEXT,
    bio             TEXT,
    avatar_url      TEXT,
    deleted_at      TIMESTAMPTZ,                    -- soft delete; every read filters on it
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Case-insensitive uniqueness. Phase 06 blocks a banned email from
-- re-registering, and case-sensitive matching makes that trivially bypassable.
CREATE UNIQUE INDEX idx_users_email_lower ON users (lower(email));

-- Partial: stays tiny, and serves the admin queries that only ever look for
-- accounts which are not ACTIVE.
CREATE INDEX idx_users_status ON users (status) WHERE status <> 'ACTIVE';

-- TIMESTAMPTZ everywhere, never TIMESTAMP. Morocco shifts its clocks around
-- Ramadan and naive timestamps would silently drift by an hour twice a year.
